In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("customer_shopping_behavior.csv")

In [3]:
df.head(5)

,Unnamed: 0,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young adult,14
2,2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young adult,7
4,4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               3900 non-null   int64
 1   customer_id              3900 non-null   int64
 2   age                      3900 non-null   int64
 3   gender                   3900 non-null   object
 4   item_purchased           3900 non-null   object
 5   category                 3900 non-null   object
 6   purchase_amount_(usd)    3900 non-null   int64
 7   location                 3900 non-null   object
 8   size                     3900 non-null   object
 9   color                    3900 non-null   object
 10  season                   3900 non-null   object
 11  review_rating            3900 non-null   float64
 12  subscription_status      3900 non-null   object
 13  shipping_type            3900 non-null   object
 14  discount_applied         3900 non-null   object
 15  previous_purchases       3900 non-null   int64
 16  payment_method           3900 non-null   object
 17  frequency_of_purchases   3900 non-null   object
 18  age_group                3900 non-null   object
 19  purchase_frequency_days  3900 non-null   int64
dtypes: float64(1), int64(6), object(13)
memory usage: 609.5+ KB

In [5]:
df.isnull().sum()

Unnamed: 0                 0
customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount_(usd)      0
location                   0
size                       0
color                      0
season                     0
review_rating              0
subscription_status        0
shipping_type              0
discount_applied           0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
age_group                  0
purchase_frequency_days    0
dtype: int64

In [6]:
df.describe()

,Unnamed: 0,customer_id,age,purchase_amount_(usd),review_rating,previous_purchases,purchase_frequency_days
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1949.500000,1950.500000,44.068462,59.764359,3.750051,25.351538,89.133077
std,1125.977353,1125.977353,15.207589,23.685392,0.713590,14.447125,119.037566
min,0.000000,1.000000,18.000000,20.000000,2.500000,1.000000,7.000000
25%,974.750000,975.750000,31.000000,39.000000,3.100000,13.000000,14.000000
50%,1949.500000,1950.500000,44.000000,60.000000,3.800000,25.000000,30.000000
75%,2924.250000,2925.250000,57.000000,81.000000,4.400000,38.000000,90.000000
max,3899.000000,3900.000000,70.000000,100.000000,5.000000,50.000000,365.000000

In [7]:
df["review_rating"] =df.groupby("category")["review_rating"].transform(lambda x: x.fillna(x.median()))

In [8]:
df.isnull().sum()

Unnamed: 0                 0
customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount_(usd)      0
location                   0
size                       0
color                      0
season                     0
review_rating              0
subscription_status        0
shipping_type              0
discount_applied           0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
age_group                  0
purchase_frequency_days    0
dtype: int64

In [9]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [10]:
df.head(3)

,unnamed:_0,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young adult,14
2,2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7

In [11]:
df.columns

Index(['unnamed:_0', 'customer_id', 'age', 'gender', 'item_purchased',
       'category', 'purchase_amount_(usd)', 'location', 'size', 'color',
       'season', 'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

#creating a column age_group

In [12]:
labels = ['Young adult','Adult','Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'],q=4,labels = labels)

In [13]:
df[['age','age_group']].head(5)

   age    age_group
0   55  Middle-aged
1   19  Young adult
2   50  Middle-aged
3   21  Young adult
4   45  Middle-aged

purchase_frquency

In [14]:
frequency_mapping = {
    "Fortnightly":14,
    "Weekly":7,
    "Monthly":30,
    "Quarterly":90,
    "Bi-Weekly":14,
    "Annually":365,
    "Every 3 Months":90
}
df['purchase_frequency_days'] = df["frequency_of_purchases"].map(frequency_mapping)

In [15]:
df.head(5)

,unnamed:_0,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young adult,14
2,2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young adult,7
4,4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365

In [16]:
df.columns

Index(['unnamed:_0', 'customer_id', 'age', 'gender', 'item_purchased',
       'category', 'purchase_amount_(usd)', 'location', 'size', 'color',
       'season', 'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [17]:
  df.to_csv("final_output.csv")

In [18]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (26.7.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~lotly (C:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~lotly (C:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~lotly (C:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [19]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (1.2.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~lotly (C:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~lotly (C:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~lotly (C:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (2.0.52)
Requirement already satisfied: greenlet>=1 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.14.1)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~lotly (C:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~lotly (C:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~lotly (C:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [21]:
from urllib.parse import quote_plus
from sqlalchemy import create_engine,text
username = "root"
password = quote_plus("Aditya00987@@")  # encodes special characters safely
host = "localhost"
port = "3306"
database = "custo_101"

engine = create_engine(f"mysql+mysqlconnector://{username}:{password}@{host}:{port}/{database}")

In [22]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT 1"))
    print(result.fetchone())

(1,)

In [23]:
table_name = "customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)

3900

In [24]:
df.head(5)

,unnamed:_0,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young adult,14
2,2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young adult,7
4,4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365